from app.models import Lead, Buyer
from sqlalchemy.orm import Session


def seed_buyers(db: Session):
    buyers = [
        Buyer(
            buyer_id="buyer-a",
            buyer_name="Buyer A - Always Accepts",
            status="active",
            balance=500.0,
            daily_cap=20,
            leads_received_today=0,
            allowed_states=["FL", "TX", "CA", "NY", "OH"],
            allowed_verticals=["Life Insurance", "Health Insurance", "Auto Insurance"],
            schedule_start="00:00",
            schedule_end="23:59",
            campaign_active=True,
            ping_tree_assigned=True,
            priority=3,
            price_per_lead=25.0,
            webhook_behavior="accept",
        ),
        Buyer(
            buyer_id="buyer-b",
            buyer_name="Buyer B - Rejects Duplicates",
            status="active",
            balance=300.0,
            daily_cap=15,
            leads_received_today=0,
            allowed_states=["FL", "TX", "CA"],
            allowed_verticals=["Life Insurance", "Health Insurance"],
            schedule_start="00:00",
            schedule_end="23:59",
            campaign_active=True,
            ping_tree_assigned=True,
            priority=1,
            price_per_lead=30.0,
            webhook_behavior="reject_duplicate",
        ),
        Buyer(
            buyer_id="buyer-c",
            buyer_name="Buyer C - Timeout",
            status="active",
            balance=400.0,
            daily_cap=10,
            leads_received_today=0,
            allowed_states=["FL", "TX", "NY"],
            allowed_verticals=["Life Insurance", "Auto Insurance"],
            schedule_start="00:00",
            schedule_end="23:59",
            campaign_active=True,
            ping_tree_assigned=True,
            priority=2,
            price_per_lead=20.0,
            webhook_behavior="timeout",
        ),
        Buyer(
            buyer_id="buyer-d",
            buyer_name="Buyer D - Low Balance",
            status="active",
            balance=5.0,
            daily_cap=10,
            leads_received_today=0,
            allowed_states=["FL", "TX", "CA", "NY"],
            allowed_verticals=["Life Insurance", "Health Insurance", "Auto Insurance"],
            schedule_start="00:00",
            schedule_end="23:59",
            campaign_active=True,
            ping_tree_assigned=True,
            priority=4,
            price_per_lead=25.0,
            webhook_behavior="accept",
        ),
        Buyer(
            buyer_id="buyer-e",
            buyer_name="Buyer E - Cap Full / Inactive",
            status="active",
            balance=600.0,
            daily_cap=5,
            leads_received_today=5,
            allowed_states=["FL", "TX", "CA", "NY", "OH"],
            allowed_verticals=["Life Insurance", "Health Insurance"],
            schedule_start="00:00",
            schedule_end="23:59",
            campaign_active=False,
            ping_tree_assigned=True,
            priority=5,
            price_per_lead=15.0,
            webhook_behavior="accept",
        ),
    ]
    for buyer in buyers:
        existing = db.query(Buyer).filter_by(buyer_id=buyer.buyer_id).first()
        if not existing:
            db.add(buyer)
    db.commit()
    return buyers


def seed_leads():
    return [
        {
            "first_name": "John",
            "last_name": "Smith",
            "phone": "3051234567",
            "email": "john.smith@example.com",
            "state": "FL",
            "vertical": "Life Insurance",
            "source": "google_ads",
            "trusted_form_cert_url": "https://cert.trustedform.com/abc123",
        },
        {
            "first_name": "Maria",
            "last_name": "Garcia",
            "phone": "7131234567",
            "email": "maria.garcia@example.com",
            "state": "TX",
            "vertical": "Health Insurance",
            "source": "facebook",
            "jornaya_lead_id": "jorn-001",
        },
        {
            "first_name": "James",
            "last_name": "Johnson",
            "phone": "2121234567",
            "email": "james.j@example.com",
            "state": "NY",
            "vertical": "Auto Insurance",
            "source": "organic",
            "trusted_form_cert_url": "https://cert.trustedform.com/def456",
        },
        {
            "first_name": "Sarah",
            "last_name": "Williams",
            "phone": "4151234567",
            "email": "sarah.w@example.com",
            "state": "CA",
            "vertical": "Life Insurance",
            "source": "referral",
            "jornaya_lead_id": "jorn-002",
        },
        {
            "first_name": "Robert",
            "last_name": "Brown",
            "phone": "6141234567",
            "email": "robert.b@example.com",
            "state": "OH",
            "vertical": "Health Insurance",
            "source": "google_ads",
            "trusted_form_cert_url": "https://cert.trustedform.com/ghi789",
        },
        {
            "first_name": "Emily",
            "last_name": "Davis",
            "phone": "3052345678",
            "email": "emily.d@example.com",
            "state": "FL",
            "vertical": "Life Insurance",
            "source": "facebook",
            "jornaya_lead_id": "jorn-003",
        },
        {
            "first_name": "Michael",
            "last_name": "Wilson",
            "phone": "7132345678",
            "email": "michael.w@example.com",
            "state": "TX",
            "vertical": "Auto Insurance",
            "source": "organic",
            "trusted_form_cert_url": "https://cert.trustedform.com/jkl012",
        },
        {
            "first_name": "Jennifer",
            "last_name": "Martinez",
            "phone": "2122345678",
            "email": "jennifer.m@example.com",
            "state": "NY",
            "vertical": "Life Insurance",
            "source": "google_ads",
            "jornaya_lead_id": "jorn-004",
        },
        {
            "first_name": "David",
            "last_name": "Anderson",
            "phone": "4152345678",
            "email": "david.a@example.com",
            "state": "CA",
            "vertical": "Health Insurance",
            "source": "referral",
            "trusted_form_cert_url": "https://cert.trustedform.com/mno345",
        },
        {
            "first_name": "Lisa",
            "last_name": "Taylor",
            "phone": "3051234567",
            "email": "lisa.t@example.com",
            "state": "FL",
            "vertical": "Life Insurance",
            "source": "facebook",
            "jornaya_lead_id": "jorn-005",
        },
    ]
